// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// IGroth16Verifier is the interface for the verifier contract generated by snarkjs.
// The generated contract has one function: verifyProof.
interface IGroth16Verifier {
    function verifyProof(
        uint[2] calldata pA,
        uint[2][2] calldata pB,
        uint[2] calldata pC,
        uint[2] calldata pubSignals
    ) external view returns (bool);
}

contract AegisAccount {

    // owner is the Ethereum address that deployed this account.
    // Only the owner can call admin functions.
    address public immutable owner;

    // oracle is the Ethereum address authorized to call deprecateECDSA.
    address public oracle;

    // verifier is the deployed Groth16Verifier contract address.
    IGroth16Verifier public immutable verifier;

    // pubKeyHash is the keccak256 hash of the agent's PQ public key (1952 bytes).
    // This is set at deployment and never changes.
    bytes32 public immutable pubKeyHash;

    // ecdsaActive starts as true. When set to false by the oracle,
    // the account no longer accepts ECDSA-signed operations — only ZK proofs.
    bool public ecdsaActive;

    // nonce prevents replay attacks. Each operation must use the current nonce.
    uint256 public nonce;

    // OperationExecuted is emitted after a successful verified operation.
    event OperationExecuted(address indexed target, uint256 value, bytes data, uint256 nonce);

    // ECDADeprecated is emitted when the oracle deprecates ECDSA.
    event ECDADeprecated(uint256 timestamp);

    // constructor sets all immutable values.
    // _owner: the Ethereum address that owns this account
    // _oracle: the address allowed to call deprecateECDSA
    // _verifier: the deployed Groth16Verifier contract address
    // _pubKeyHash: keccak256 of the agent's PQ public key, as bytes32
    constructor(
        address _owner,
        address _oracle,
        address _verifier,
        bytes32 _pubKeyHash
    ) {
        owner = _owner;
        oracle = _oracle;
        verifier = IGroth16Verifier(_verifier);
        pubKeyHash = _pubKeyHash;
        ecdsaActive = true;
        nonce = 0;
    }

    // deprecateECDSA can only be called by the oracle address.
    // After this is called, executeWithECDSA will always revert.
    function deprecateECDSA() external {
        require(msg.sender == oracle, "AegisAccount: caller is not oracle");
        ecdsaActive = false;
        emit ECDADeprecated(block.timestamp);
    }

    // executeWithZKProof verifies a Groth16 proof and executes an operation if valid.
    //
    // Parameters:
    //   pA, pB, pC: the Groth16 proof components, formatted as returned by
    //               AegisProver.formatProofForSolidity()
    //   commitment: the Poseidon commitment — publicSignals[0] from the proof
    //   target: the contract address to call
    //   value: the ETH value to send with the call (0 for most operations)
    //   data: the ABI-encoded calldata to send to target
    //
    // The function:
    //   1. Converts pubKeyHash (bytes32) to uint256 for the circuit's public signal
    //   2. Calls verifier.verifyProof with the proof and [commitment, pubKeyHashUint]
    //   3. If the proof is invalid, reverts with "AegisAccount: invalid ZK proof"
    //   4. If valid, increments nonce and executes the call to target
    function executeWithZKProof(
        uint[2] calldata pA,
        uint[2][2] calldata pB,
        uint[2] calldata pC,
        uint256 commitment,
        address target,
        uint256 value,
        bytes calldata data
    ) external returns (bytes memory) {
        // Convert bytes32 pubKeyHash to uint256 for the verifier
        uint256 pubKeyHashUint = uint256(pubKeyHash);

        // Mask to 128 bits to match what the TypeScript prover computes
        uint256 mask128 = (1 << 128) - 1;
        uint256 pubKeyHashField = pubKeyHashUint & mask128;

        // Build the public signals array: [commitment, pubKeyHashField]
        uint[2] memory pubSignals;
        pubSignals[0] = commitment;
        pubSignals[1] = pubKeyHashField;

        // Verify the proof
        bool valid = verifier.verifyProof(pA, pB, pC, pubSignals);
        require(valid, "AegisAccount: invalid ZK proof");

        // Increment nonce to prevent replay
        uint256 currentNonce = nonce;
        nonce++;

        // Execute the operation
        (bool success, bytes memory result) = target.call{value: value}(data);
        require(success, "AegisAccount: operation execution failed");

        emit OperationExecuted(target, value, data, currentNonce);
        return result;
    }

    // executeWithECDSA is the hybrid fallback. It works only when ecdsaActive is true.
    // sig is a standard Ethereum ECDSA signature (65 bytes, produced by ethers.signMessage).
    // messageHash is the hash that was signed.
    // target, value, data are the operation to execute.
    function executeWithECDSA(
        bytes calldata sig,
        bytes32 messageHash,
        address target,
        uint256 value,
        bytes calldata data
    ) external returns (bytes memory) {
        require(ecdsaActive, "AegisAccount: ECDSA has been deprecated");

        // Recover the signer from the signature
        bytes32 ethHash = keccak256(abi.encodePacked("\x19Ethereum Signed Message:\n32", messageHash));
        address recovered = recoverSigner(ethHash, sig);
        require(recovered == owner, "AegisAccount: invalid ECDSA signature");

        uint256 currentNonce = nonce;
        nonce++;

        (bool success, bytes memory result) = target.call{value: value}(data);
        require(success, "AegisAccount: operation execution failed");

        emit OperationExecuted(target, value, data, currentNonce);
        return result;
    }

    // recoverSigner splits an ECDSA signature and calls ecrecover.
    // sig must be exactly 65 bytes: r (32 bytes) + s (32 bytes) + v (1 byte).
    function recoverSigner(bytes32 hash, bytes calldata sig) internal pure returns (address) {
        require(sig.length == 65, "AegisAccount: invalid signature length");
        bytes32 r;
        bytes32 s;
        uint8 v;
        assembly {
            r := calldataload(sig.offset)
            s := calldataload(add(sig.offset, 32))
            v := byte(0, calldataload(add(sig.offset, 64)))
        }
        return ecrecover(hash, v, r, s);
    }

    // receive allows the contract to hold ETH.
    receive() external payable {}
}
