import { buildModule } from "@nomicfoundation/hardhat-ignition/modules";

/**
 * Groth16VerifierModule
 * Deploys the Groth16Verifier contract generated by snarkjs.
 * This contract verifies BN254 pairing proofs on-chain.
 * Deploy this first — AegisAccount depends on its address.
 */
const Groth16VerifierModule = buildModule("Groth16VerifierModule", (m) => {
  const verifier = m.contract("Groth16Verifier", []);
  return { verifier };
});

export default Groth16VerifierModule;
